//SECTION 2
export const Sec2CardInfo = [
  {
    id: "automation-solutions",
    src: "/X_icon.png",
    alt: "",
    title: "Automation Solutions",
    icon: "/X_icon.png",
    href: "/service/automation-solutions",
    desc: "We provide customized solutions that integrate with your existing system and improve your overall workflow.",
    desc2: `XTechnology offers automation solutions that increase the efficiency and productivity of your operations. Our automation systems are designed to streamline your processes and reduce manual labor. We provide customized solutions that integrate with your existing system and improve your overall workflow.`,
  },
{
  id: "panel-fabrication",
  src: "/berard_lift_stationPanel.png",
  alt: "Custom UL-listed control panel fabrication",
  title: "Panel Fabrication",
  icon: "/X_icon.png",
  href: "/service/panel-fabrication",
  desc: "Custom UL-listed panel fabrication built to certified safety and quality standards.",
  desc2: `We design and fabricate industrial control panels that are UL-listed and certified for safety, reliability, and compliance. Each panel is custom-built with quality components, precision wiring, and thorough testing to ensure long-lasting performance. From concept to delivery, our certified panel shop provides documentation and support so your operations meet the highest industry standards.`
},
  {
    id: "control-system",
    src: "/X_icon.png",
    alt: "",
    title: "Control System Design",
    icon: "/X_icon.png",
    href: "/service/control-system",
    desc: "Our systems are designed to be user-friendly, easy to maintain, and reliable in any environment.",
    desc2: `We specialize in control system design and implementation, providing complete turnkey solutions. Our team of experts will work with you to develop a system that meets your requirements and specifications, ensuring reliable, efficient, and cost-effective operation. Our systems are designed to be user-friendly, easy to maintain, and reliable in any environment.`,
  },
  {
    id: "scada",
    src: "/X_icon.png",
    alt: "",
    title: "SCADA",
    icon: "/X_icon.png",
    href: "/service/scada",
    desc: "Businesses can monitor and manage their operations from anywhere in the world.",
    desc2: `SCADA is an advanced technology that enables remote monitoring and control of industrial processes. It provides real-time data acquisition, advanced analytics, and automated control of processes, allowing businesses to increase efficiency and productivity. With SCADA, businesses can monitor and manage their operations from anywhere in the world.`,
  },
  {
    id: "communications",
    src: "/X_icon.png",
    alt: "",
    title: "Communications",
    icon: "/X_icon.png",
    href: "/service/communications",
    desc: "Seamless integration of industrial protocols ensuring reliable data flow between field devices.",
    desc2: `We specialize in implementing and troubleshooting a wide range of industrial communication protocols including 4–20mA, HART, RS-485, Modbus RTU/TCP, and more. Whether you're integrating smart sensors, connecting PLCs, or building out SCADA systems, we ensure accurate, reliable signal transmission and device interoperability`,
  },
  {
    id: "project-management",
    src: "/X_icon.png",
    alt: "",
    title: "Project Management",
    icon: "/X_icon.png",
    href: "/service/project-management",
    desc: "Our team streamlines workflows, manages resources effectively, and tailors each project to fit your infrastructure.",
    desc2: `At XTechnology, we comprehend the significance of staying ahead in the rapidly evolving automation landscape. Utilizing cutting-edge tools and employing innovative strategies, we navigate the complexities of project management, guaranteeing optimal outcomes and enhanced productivity.
            Our adept professionals, well-versed in the art of project coordination and resource allocation, employ a thorough approach to streamline workflows, minimize risks, and deliver projects within stipulated timelines and budgets. We adapt to the unique requirements of your organization, ensuring seamless integration of automation solutions into your existing infrastructure.`,
  },
  {
    id: "consulting",
    src: "/X_icon.png",
    alt: "",
    title: "Consulting",
    icon: "/X_icon.png",
    href: "/service/consulting",
    desc: "Our experienced staff can help you identify the right technologies to optimize your operations and maximize your resources.",
    desc2: `Our Consulting service provides expert advice on the best solutions for your organization. Our experienced staff can help you identify the right technologies to optimize your operations and maximize your resources. We offer tailored strategies to ensure your automation project is successful and cost-effective.`,
  },
  {
    id: "power-generation",
    src: "/vfd_skid.JPG",
    alt: "",
    title: "Power Generation and Engine Control",
    icon: "/X_icon.png",
    href: "/service/power-generation",
    desc: "Our team will work with you to design and implement a custom solution to ensure your operations remain efficient and reliable.",
    desc2: `We provide custom packages for power generation and engine control systems that can help you optimize your production. Our experienced team will work with you to design and implement a custom solution to ensure your operations remain efficient and reliable. Our solutions are designed to maximize efficiency while minimizing downtime and maintenance costs.`,
  },
  {
    id: "commissioning",
    src: "/X_icon.png",
    alt: "",
    title: "Commissioning and Startup",
    icon: "/X_icon.png",
    href: "/service/commissioning",
    desc: "We provide the necessary adjustments to get your system up and running with maximum efficiency.",
    desc2: `Our Commissioning and Startup service ensures that all control systems are correctly installed and are running as expected. Our team of experienced staff of specialists will provide am extensive analysis of the system and provide the necessary adjustments to get your system up and running with maximum efficiency. We guarantee that your control system will be ready to use after our Commissioning and Startup service.`,
  },
  {
    id: "i-e-services",
    src: "/X_icon.png",
    alt: "",
    title: "I&E Services ",
    icon: "/X_icon.png",
    href: "/service/i-e-services",
    desc: "Robust, high-performance control systems with a focus on precision and quality.",
    desc2: `Our I & E services deliver robust, high-performance control systems with a focus on precision and quality. Our expertise includes: Panel Manufacturing & System Fabrication, Precise Tubing & Cable Installation and Termination, Process & Subsea Control System Installations, Nationwide & Offshore Service Availability`,
  },
  {
    id: "service-call-outs",
    src: "/X_icon.png",
    alt: "",
    title: "Service Call-Outs",
    icon: "/X_icon.png",
    href: "/service/service-call-outs",
    desc: "Our team provides rapid, reliable on-demand support to resolve your critical system issues.",
    desc2: `Our team provides rapid, reliable on-demand support to resolve your critical system issues, from emergency call-outs to long-term maintenance, ensuring your operations get back online efficiently.`,
  },
];
