import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import { Navbar, Footer, PhoneNumber } from "@/components/index";
import { Roboto } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import styles from "@/style";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "X Technology-USA",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/X_icon.png", sizes: "any" }],
  },
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-Roboto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Toaster position="top-center" reverseOrder={false} />

        <div className="bg-black w-full">
          <PhoneNumber />
          <div className={`${styles.paddingX} ${styles.flexCenter}`}>
            <div className={`${styles.boxWidth} z-[10]`}>
              <Navbar />
            </div>
          </div>
        </div>

        <main className="relative overflow-hidden bg-white">
          {children}
        </main>

        <div className={`${styles.paddingX} ${styles.flexCenter} bg-black`}>
          <div className={`${styles.boxWidth}`}>
            <Footer />
          </div>
        </div>

        <SpeedInsights />
      </body>
    </html>
  );
}
