import type { Metadata } from "next";
import Head from "next/head";
import "./globals.css";
import { Navbar, CTA, Footer } from "@/components/index";
import { Amatic_SC } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";

import styles from "@/style";

export const metadata: Metadata = {
  title: "X Technology-USA",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/X_icon.png", sizes: "any" }],
  },
};

const amatic = Amatic_SC({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-Amatic_SC",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="bg-black w-full">
          <div className={`${styles.paddingX} ${styles.flexCenter}`}>
            <div className={`${styles.boxWidth} z-[10]`}>
              <Navbar />
            </div>
          </div>
        </div>
        <main className={`${amatic.variable} relative overflow-hidden`}>
          {children}
        </main>
        <CTA/>
        <div className={`${styles.paddingX} ${styles.flexCenter} bg-black`}>
          <div className={`${styles.boxWidth}`}>
            <Footer />
          </div>
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}
